export const FETCH_GITHUB_USER_ERROR   = 'FETCH_GITHUB_USER_ERROR';
export const FETCH_GITHUB_USER_LOADING = 'FETCH_GITHUB_USER_LOADING';
export const FETCH_GITHUB_USER_SUCCESS = 'FETCH_GITHUB_USER_SUCCESS';

export const GET_USER_ERROR   = 'GET_USER_ERROR';
export const GET_USER_LOADING = 'GET_USER_LOADING';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';

export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
